name = "music-video-platform"
compatibility_date = "2026-07-13"
main = "./workers.js"

[assets]
directory = "frontend/dist"
not_found_handling = "single-page-application"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "music-audio-storage"

[vars]
API_BASE_URL = "https://ai-music-backend-db6h.onrender.com"
RATE_LIMIT = "100"
CORS_ORIGIN = "https://music-video-platform.zezhending90.workers.dev"