"""一次性注入脚本：为全部 12 个语种新增 `share` 命名空间（分享落地页文案）。

背景
----
`SharePage.tsx` 此前的按钮文案是**硬编码中文**（"分享" / "下载封面卡" / "去做一首
自己的歌" …）。而分享落地页恰恰是**陌生访客的第一屏** —— 他们多半来自其它语言区，
看到中文会直接关掉，病毒飞轮在这里断掉。所以随「分享到其他平台」一起做 i18n。

口径
----
- 键序固定（以本文件的 _KEYS 为准），保证 12 个语种键序一致、便于 diff
- 平台名（WeChat/Weibo/QQ/X/Facebook/WhatsApp/Telegram/Reddit/LinkedIn/Pinterest）
  在非中文语种保留**拉丁原名**（品牌名不意译）；zh 用「微信/微博/QQ」。
  ⚠️ 因此 parity_check.py 会把这些键在非 en 语种里计为 untranslated —— 属**预期
  假阳性**，与 appName=Melovar 同理。
- `shareText` 保留 `{title}` / `{url}` 占位符，交给 useTranslation 的 {x} 替换
- 幂等：重复执行结果一致；已存在同名命名空间则整体按 _KEYS 重建（不追加垃圾键）

用法
----
    python frontend/src/i18n/add_share_ns.py          # 写入
    python frontend/src/i18n/add_share_ns.py --check  # 只校验不写入
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

LOCALES = Path(__file__).resolve().parent / "locales"

# 键序：12 个语种严格一致
_KEYS = (
    "notFound",
    "goCreate",
    "loading",
    "shareTo",
    "systemShare",
    "copyLink",
    "linkCopied",
    "copyText",
    "textCopied",
    "downloadCover",
    "downloadAudio",
    "wechat",
    "weibo",
    "qq",
    "x",
    "facebook",
    "whatsapp",
    "telegram",
    "reddit",
    "linkedin",
    "pinterest",
    "wechatTitle",
    "wechatHint",
    "scanQr",
    "close",
    "hook",
    "cta",
    "shareText",
)

T: dict[str, dict[str, str]] = {
    "en": {
        "notFound": "This share link is invalid or has expired",
        "goCreate": "Create your own song",
        "loading": "Loading…",
        "shareTo": "Share to",
        "systemShare": "Share…",
        "copyLink": "Copy link",
        "linkCopied": "Link copied",
        "copyText": "Copy caption",
        "textCopied": "Caption copied",
        "downloadCover": "Download cover",
        "downloadAudio": "Download audio",
        "wechat": "WeChat",
        "weibo": "Weibo",
        "qq": "QQ",
        "x": "X",
        "facebook": "Facebook",
        "whatsapp": "WhatsApp",
        "telegram": "Telegram",
        "reddit": "Reddit",
        "linkedin": "LinkedIn",
        "pinterest": "Pinterest",
        "wechatTitle": "Share to WeChat",
        "wechatHint": "Scan the QR code with WeChat, or copy the link and paste it to a friend.",
        "scanQr": "Scan to open",
        "close": "Close",
        "hook": "This song was generated by AI. Type one sentence and you can make your own.",
        "cta": "Make one like this — free",
        "shareText": "{title}\nAI-generated music · Make your own in one sentence with Melovar\n{url}",
    },
    "zh": {
        "notFound": "这个分享链接无效或已失效",
        "goCreate": "去做一首自己的歌",
        "loading": "加载中…",
        "shareTo": "分享到",
        "systemShare": "系统分享",
        "copyLink": "复制链接",
        "linkCopied": "链接已复制",
        "copyText": "复制文案",
        "textCopied": "文案已复制",
        "downloadCover": "下载封面卡",
        "downloadAudio": "下载音频",
        "wechat": "微信",
        "weibo": "微博",
        "qq": "QQ",
        "x": "X",
        "facebook": "Facebook",
        "whatsapp": "WhatsApp",
        "telegram": "Telegram",
        "reddit": "Reddit",
        "linkedin": "LinkedIn",
        "pinterest": "Pinterest",
        "wechatTitle": "分享到微信",
        "wechatHint": "用微信「扫一扫」扫描二维码，或复制链接后粘贴给好友。",
        "scanQr": "扫码打开",
        "close": "关闭",
        "hook": "这首歌由 AI 生成。输入一句话，你也能做出自己的歌。",
        "cta": "免费做一首同款",
        "shareText": "{title}\nAI 生成音乐 · 用 Melovar 一句话做自己的歌\n{url}",
    },
    "ja": {
        "notFound": "この共有リンクは無効か、有効期限が切れています",
        "goCreate": "自分の曲を作る",
        "loading": "読み込み中…",
        "shareTo": "シェアする",
        "systemShare": "シェア…",
        "copyLink": "リンクをコピー",
        "linkCopied": "リンクをコピーしました",
        "copyText": "テキストをコピー",
        "textCopied": "テキストをコピーしました",
        "downloadCover": "カバーをダウンロード",
        "downloadAudio": "音源をダウンロード",
        "wechat": "WeChat",
        "weibo": "Weibo",
        "qq": "QQ",
        "x": "X",
        "facebook": "Facebook",
        "whatsapp": "WhatsApp",
        "telegram": "Telegram",
        "reddit": "Reddit",
        "linkedin": "LinkedIn",
        "pinterest": "Pinterest",
        "wechatTitle": "WeChat でシェア",
        "wechatHint": "WeChat の「スキャン」で QR コードを読み取るか、リンクをコピーして友だちに送ってください。",
        "scanQr": "スキャンして開く",
        "close": "閉じる",
        "hook": "この曲は AI が生成しました。ひと言入力するだけで、あなたも自分の曲を作れます。",
        "cta": "同じような曲を無料で作る",
        "shareText": "{title}\nAI 生成音楽 · Melovar ならひと言で自分の曲が作れます\n{url}",
    },
    "ko": {
        "notFound": "이 공유 링크는 유효하지 않거나 만료되었습니다",
        "goCreate": "내 노래 만들기",
        "loading": "불러오는 중…",
        "shareTo": "공유하기",
        "systemShare": "공유…",
        "copyLink": "링크 복사",
        "linkCopied": "링크를 복사했습니다",
        "copyText": "문구 복사",
        "textCopied": "문구를 복사했습니다",
        "downloadCover": "커버 다운로드",
        "downloadAudio": "음원 다운로드",
        "wechat": "WeChat",
        "weibo": "Weibo",
        "qq": "QQ",
        "x": "X",
        "facebook": "Facebook",
        "whatsapp": "WhatsApp",
        "telegram": "Telegram",
        "reddit": "Reddit",
        "linkedin": "LinkedIn",
        "pinterest": "Pinterest",
        "wechatTitle": "WeChat으로 공유",
        "wechatHint": "WeChat '스캔'으로 QR 코드를 찍거나, 링크를 복사해 친구에게 붙여넣으세요.",
        "scanQr": "스캔하여 열기",
        "close": "닫기",
        "hook": "이 노래는 AI가 만들었습니다. 한 문장만 입력하면 나만의 노래를 만들 수 있어요.",
        "cta": "같은 스타일로 무료로 만들기",
        "shareText": "{title}\nAI 생성 음악 · Melovar에서 한 문장으로 나만의 노래를\n{url}",
    },
    "es": {
        "notFound": "Este enlace para compartir no es válido o ha caducado",
        "goCreate": "Crea tu propia canción",
        "loading": "Cargando…",
        "shareTo": "Compartir en",
        "systemShare": "Compartir…",
        "copyLink": "Copiar enlace",
        "linkCopied": "Enlace copiado",
        "copyText": "Copiar texto",
        "textCopied": "Texto copiado",
        "downloadCover": "Descargar portada",
        "downloadAudio": "Descargar audio",
        "wechat": "WeChat",
        "weibo": "Weibo",
        "qq": "QQ",
        "x": "X",
        "facebook": "Facebook",
        "whatsapp": "WhatsApp",
        "telegram": "Telegram",
        "reddit": "Reddit",
        "linkedin": "LinkedIn",
        "pinterest": "Pinterest",
        "wechatTitle": "Compartir en WeChat",
        "wechatHint": "Escanea el código QR con WeChat o copia el enlace y pégalo en el chat.",
        "scanQr": "Escanea para abrir",
        "close": "Cerrar",
        "hook": "Esta canción la generó una IA. Escribe una frase y podrás crear la tuya.",
        "cta": "Crea una gratis",
        "shareText": "{title}\nMúsica generada por IA · Crea la tuya con una frase en Melovar\n{url}",
    },
    "fr": {
        "notFound": "Ce lien de partage est invalide ou a expiré",
        "goCreate": "Créez votre propre chanson",
        "loading": "Chargement…",
        "shareTo": "Partager sur",
        "systemShare": "Partager…",
        "copyLink": "Copier le lien",
        "linkCopied": "Lien copié",
        "copyText": "Copier le texte",
        "textCopied": "Texte copié",
        "downloadCover": "Télécharger la pochette",
        "downloadAudio": "Télécharger l'audio",
        "wechat": "WeChat",
        "weibo": "Weibo",
        "qq": "QQ",
        "x": "X",
        "facebook": "Facebook",
        "whatsapp": "WhatsApp",
        "telegram": "Telegram",
        "reddit": "Reddit",
        "linkedin": "LinkedIn",
        "pinterest": "Pinterest",
        "wechatTitle": "Partager sur WeChat",
        "wechatHint": "Scannez le QR code avec WeChat, ou copiez le lien et envoyez-le à un ami.",
        "scanQr": "Scannez pour ouvrir",
        "close": "Fermer",
        "hook": "Cette chanson a été générée par une IA. Écrivez une phrase et créez la vôtre.",
        "cta": "Créez la vôtre gratuitement",
        "shareText": "{title}\nMusique générée par IA · Créez la vôtre en une phrase avec Melovar\n{url}",
    },
    "pt": {
        "notFound": "Este link de compartilhamento é inválido ou expirou",
        "goCreate": "Crie sua própria música",
        "loading": "Carregando…",
        "shareTo": "Compartilhar em",
        "systemShare": "Compartilhar…",
        "copyLink": "Copiar link",
        "linkCopied": "Link copiado",
        "copyText": "Copiar texto",
        "textCopied": "Texto copiado",
        "downloadCover": "Baixar capa",
        "downloadAudio": "Baixar áudio",
        "wechat": "WeChat",
        "weibo": "Weibo",
        "qq": "QQ",
        "x": "X",
        "facebook": "Facebook",
        "whatsapp": "WhatsApp",
        "telegram": "Telegram",
        "reddit": "Reddit",
        "linkedin": "LinkedIn",
        "pinterest": "Pinterest",
        "wechatTitle": "Compartilhar no WeChat",
        "wechatHint": "Escaneie o QR code com o WeChat ou copie o link e envie para um amigo.",
        "scanQr": "Escaneie para abrir",
        "close": "Fechar",
        "hook": "Esta música foi gerada por IA. Escreva uma frase e crie a sua.",
        "cta": "Crie uma grátis",
        "shareText": "{title}\nMúsica gerada por IA · Crie a sua em uma frase no Melovar\n{url}",
    },
    "ru": {
        "notFound": "Эта ссылка недействительна или устарела",
        "goCreate": "Создать свою песню",
        "loading": "Загрузка…",
        "shareTo": "Поделиться в",
        "systemShare": "Поделиться…",
        "copyLink": "Скопировать ссылку",
        "linkCopied": "Ссылка скопирована",
        "copyText": "Скопировать текст",
        "textCopied": "Текст скопирован",
        "downloadCover": "Скачать обложку",
        "downloadAudio": "Скачать аудио",
        "wechat": "WeChat",
        "weibo": "Weibo",
        "qq": "QQ",
        "x": "X",
        "facebook": "Facebook",
        "whatsapp": "WhatsApp",
        "telegram": "Telegram",
        "reddit": "Reddit",
        "linkedin": "LinkedIn",
        "pinterest": "Pinterest",
        "wechatTitle": "Поделиться в WeChat",
        "wechatHint": "Отсканируйте QR-код в WeChat или скопируйте ссылку и отправьте её другу.",
        "scanQr": "Отсканируйте, чтобы открыть",
        "close": "Закрыть",
        "hook": "Эту песню создал ИИ. Введите одну фразу — и у вас будет своя.",
        "cta": "Создать такую же бесплатно",
        "shareText": "{title}\nМузыка, созданная ИИ · Своя песня из одной фразы в Melovar\n{url}",
    },
    "de": {
        "notFound": "Dieser Freigabelink ist ungültig oder abgelaufen",
        "goCreate": "Erstelle deinen eigenen Song",
        "loading": "Wird geladen…",
        "shareTo": "Teilen auf",
        "systemShare": "Teilen…",
        "copyLink": "Link kopieren",
        "linkCopied": "Link kopiert",
        "copyText": "Text kopieren",
        "textCopied": "Text kopiert",
        "downloadCover": "Cover herunterladen",
        "downloadAudio": "Audio herunterladen",
        "wechat": "WeChat",
        "weibo": "Weibo",
        "qq": "QQ",
        "x": "X",
        "facebook": "Facebook",
        "whatsapp": "WhatsApp",
        "telegram": "Telegram",
        "reddit": "Reddit",
        "linkedin": "LinkedIn",
        "pinterest": "Pinterest",
        "wechatTitle": "Auf WeChat teilen",
        "wechatHint": "Scanne den QR-Code mit WeChat oder kopiere den Link und sende ihn an Freunde.",
        "scanQr": "Zum Öffnen scannen",
        "close": "Schließen",
        "hook": "Dieser Song wurde von einer KI erzeugt. Ein Satz genügt und du machst deinen eigenen.",
        "cta": "Gratis ein eigenes Lied machen",
        "shareText": "{title}\nKI-generierte Musik · Mit Melovar in einem Satz dein eigener Song\n{url}",
    },
    "hi": {
        "notFound": "यह शेयर लिंक अमान्य है या समाप्त हो चुका है",
        "goCreate": "अपना गाना बनाएँ",
        "loading": "लोड हो रहा है…",
        "shareTo": "यहाँ शेयर करें",
        "systemShare": "शेयर करें…",
        "copyLink": "लिंक कॉपी करें",
        "linkCopied": "लिंक कॉपी हो गया",
        "copyText": "कैप्शन कॉपी करें",
        "textCopied": "कैप्शन कॉपी हो गया",
        "downloadCover": "कवर डाउनलोड करें",
        "downloadAudio": "ऑडियो डाउनलोड करें",
        "wechat": "WeChat",
        "weibo": "Weibo",
        "qq": "QQ",
        "x": "X",
        "facebook": "Facebook",
        "whatsapp": "WhatsApp",
        "telegram": "Telegram",
        "reddit": "Reddit",
        "linkedin": "LinkedIn",
        "pinterest": "Pinterest",
        "wechatTitle": "WeChat पर शेयर करें",
        "wechatHint": "WeChat से QR कोड स्कैन करें, या लिंक कॉपी करके दोस्त को भेजें।",
        "scanQr": "खोलने के लिए स्कैन करें",
        "close": "बंद करें",
        "hook": "यह गाना AI ने बनाया है। एक वाक्य लिखें और अपना गाना बनाएँ।",
        "cta": "ऐसा ही गाना मुफ़्त बनाएँ",
        "shareText": "{title}\nAI से बना संगीत · Melovar पर एक वाक्य से अपना गाना बनाएँ\n{url}",
    },
    "id": {
        "notFound": "Tautan berbagi ini tidak valid atau sudah kedaluwarsa",
        "goCreate": "Buat lagu sendiri",
        "loading": "Memuat…",
        "shareTo": "Bagikan ke",
        "systemShare": "Bagikan…",
        "copyLink": "Salin tautan",
        "linkCopied": "Tautan disalin",
        "copyText": "Salin teks",
        "textCopied": "Teks disalin",
        "downloadCover": "Unduh sampul",
        "downloadAudio": "Unduh audio",
        "wechat": "WeChat",
        "weibo": "Weibo",
        "qq": "QQ",
        "x": "X",
        "facebook": "Facebook",
        "whatsapp": "WhatsApp",
        "telegram": "Telegram",
        "reddit": "Reddit",
        "linkedin": "LinkedIn",
        "pinterest": "Pinterest",
        "wechatTitle": "Bagikan ke WeChat",
        "wechatHint": "Pindai kode QR dengan WeChat, atau salin tautan dan kirim ke teman.",
        "scanQr": "Pindai untuk membuka",
        "close": "Tutup",
        "hook": "Lagu ini dibuat oleh AI. Tulis satu kalimat dan kamu bisa membuat lagumu sendiri.",
        "cta": "Buat lagu serupa gratis",
        "shareText": "{title}\nMusik buatan AI · Bikin lagumu sendiri dalam satu kalimat di Melovar\n{url}",
    },
    "ar": {
        "notFound": "رابط المشاركة هذا غير صالح أو انتهت صلاحيته",
        "goCreate": "أنشئ أغنيتك الخاصة",
        "loading": "جارٍ التحميل…",
        "shareTo": "شارك على",
        "systemShare": "مشاركة…",
        "copyLink": "نسخ الرابط",
        "linkCopied": "تم نسخ الرابط",
        "copyText": "نسخ النص",
        "textCopied": "تم نسخ النص",
        "downloadCover": "تنزيل الغلاف",
        "downloadAudio": "تنزيل الصوت",
        "wechat": "WeChat",
        "weibo": "Weibo",
        "qq": "QQ",
        "x": "X",
        "facebook": "Facebook",
        "whatsapp": "WhatsApp",
        "telegram": "Telegram",
        "reddit": "Reddit",
        "linkedin": "LinkedIn",
        "pinterest": "Pinterest",
        "wechatTitle": "المشاركة على WeChat",
        "wechatHint": "امسح رمز QR باستخدام WeChat، أو انسخ الرابط وأرسله لصديق.",
        "scanQr": "امسح للفتح",
        "close": "إغلاق",
        "hook": "هذه الأغنية من إنشاء الذكاء الاصطناعي. اكتب جملة واحدة واصنع أغنيتك.",
        "cta": "أنشئ أغنية مشابهة مجانًا",
        "shareText": "{title}\nموسيقى من إنشاء الذكاء الاصطناعي · أنشئ أغنيتك بجملة واحدة على Melovar\n{url}",
    },
}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="只校验不写入")
    args = ap.parse_args()

    problems: list[str] = []
    for lang, table in T.items():
        missing = [k for k in _KEYS if k not in table]
        extra = [k for k in table if k not in _KEYS]
        if missing:
            problems.append(f"{lang}: 缺键 {missing}")
        if extra:
            problems.append(f"{lang}: 多余键 {extra}")

    if problems:
        print("翻译表自身不自洽，已中止：")
        for p in problems:
            print("  -", p)
        return 1

    if args.check:
        print(f"翻译表自洽（{len(T)} 语种 × {len(_KEYS)} 键）。")
        for lang in T:
            data = json.loads((LOCALES / f"{lang}.json").read_text(encoding="utf-8"))
            ns = data.get("share")
            if not isinstance(ns, dict):
                print(f"  {lang}: 缺少 share 命名空间")
                return 1
            diff = [k for k in _KEYS if ns.get(k) != T[lang][k]]
            print(f"  {lang}: {'OK' if not diff else '不一致 ' + str(diff)}")
        return 0

    for lang, table in T.items():
        path = LOCALES / f"{lang}.json"
        raw = path.read_text(encoding="utf-8")
        data = json.loads(raw)
        # 按 _KEYS 重建（保证键序一致、且不残留旧键）
        data["share"] = {k: table[k] for k in _KEYS}
        out = json.dumps(data, ensure_ascii=False, indent=2) + "\n"
        path.write_text(out, encoding="utf-8")
        print(f"  {lang}.json 已写入 share（{len(_KEYS)} 键，文件 {len(raw)} -> {len(out)} 字节）")

    print("完成。")
    return 0


if __name__ == "__main__":
    sys.exit(main())
